import { Assessment } from "../shared/models/assessment";

import {
  EXAMPLE_AIR_COOLED_SYSTEM_INPUT,
  EXAMPLE_WATER_COOLED_SYSTEM_INPUT,
  EXAMPLE_TOWER_INPUT,
  EXAMPLE_SYSTEM_BASICS,
  EXAMPLE_SYSTEM_INFORMATION_OPERATIONS,
  EXAMPLE_CO2_SAVINGS_DATA,
  EXAMPLE_INVENTORY,
  EXAMPLE_PUMP_INPUT_CONDENSER,
  EXAMPLE_PUMP_INPUT_CHILLED
// } from './CWSATExampleAirCooledConstant';
} from './CWSATExampleVINPLTConstants';
import { Settings } from "../shared/models/settings";

export const MockProcessCoolingAssessment: Assessment = {
    "name": "Process Cooling Example",
    "createdDate": new Date('2025-06-18T13:39:17.170Z'),
    "modifiedDate": new Date('2025-06-18T13:39:17.170Z'),
    "type": "ProcessCooling",
    "isExample": true,
    "appVersion": "1.6.1",
    "directoryId": 2,
    "processCooling": {
        name: "Baseline",
        modifications: [],
        setupDone: true,
        systemBasics: { ...EXAMPLE_SYSTEM_BASICS },
        systemInformation: {
            co2SavingsData: {...EXAMPLE_CO2_SAVINGS_DATA},
            operations: { ...EXAMPLE_SYSTEM_INFORMATION_OPERATIONS },
            airCooledSystemInput: { ...EXAMPLE_AIR_COOLED_SYSTEM_INPUT },
            waterCooledSystemInput: { ...EXAMPLE_WATER_COOLED_SYSTEM_INPUT },
            chilledWaterPumpInput: { ...EXAMPLE_PUMP_INPUT_CHILLED },
            condenserWaterPumpInput: { ...EXAMPLE_PUMP_INPUT_CONDENSER },
            towerInput: { ...EXAMPLE_TOWER_INPUT }
        },
        inventory: [ ...EXAMPLE_INVENTORY ],
        selectedModificationId: null,
        selected: false,
        existingDataUnits: 'Imperial'
    },
    "selected": false,
}



export const MockProcessCoolingSettings: Settings = {
    "language": "English",
    "currency": "$",
    "unitsOfMeasure": "Imperial",
    "emissionsUnit": "Metric",
    "distanceMeasurement": "ft",
    "flowMeasurement": "gpm",
    "powerMeasurement": "hp",
    "pressureMeasurement": "psi",
    "steamPressureMeasurement": "psig",
    "steamTemperatureMeasurement": "F",
    "steamSpecificEnthalpyMeasurement": "btuLb",
    "steamSpecificEntropyMeasurement": "btulbF",
    "steamSpecificVolumeMeasurement": "ft3lb",
    "steamMassFlowMeasurement": "klb",
    "steamPowerMeasurement": "kW",
    "steamVolumeMeasurement": "gal",
    "steamVolumeFlowMeasurement": "gpm",
    "steamVacuumPressure": "psia",
    "currentMeasurement": null,
    "viscosityMeasurement": null,
    "voltageMeasurement": null,
    "energySourceType": "Electricity",
    "furnaceType": "Electrical Infrared",
    "energyResultUnit": "kWh",
    "customFurnaceName": null,
    "temperatureMeasurement": "F",
    "fanCurveType": null,
    "fanConvertedConditions": null,
    "phastRollupUnit": "MMBtu",
    "phastRollupFuelUnit": "MMBtu",
    "phastRollupElectricityUnit": "kWh",
    "phastRollupSteamUnit": "MMBtu",
    "defaultPanelTab": "results",
    "fuelCost": 3.99,
    "steamCost": 4.69,
    "electricityCost": 0.066,
    "densityMeasurement": "lbscf",
    "fanFlowRate": "ft3/min",
    "fanPressureMeasurement": "inH2o",
    "fanBarometricPressure": "inHg",
    "fanSpecificHeatGas": "btulbF",
    "fanPowerMeasurement": "hp",
    "fanTemperatureMeasurement": "F",
    "steamEnergyMeasurement": "MMBtu",
    "disableTutorial": true,
    "disableDashboardTutorial": false,
    "disablePsatTutorial": true,
    "disableFansTutorial": false,
    "disablePhastTutorial": true,
    "disableWasteWaterTutorial": false,
    "disableSteamTutorial": false,
    "disableMotorInventoryTutorial": false,
    "disableTreasureHuntTutorial": true,
    "disableDataExplorerTutorial": false,
    "compressedAirCost": 0.022,
    "otherFuelCost": 0,
    "waterCost": 0,
    "waterWasteCost": 0,
    "printPsatRollup": true,
    "printPhastRollup": true,
    "printFsatRollup": true,
    "printTreasureHuntRollup": true,
    "printReportGraphs": true,
    "printReportSankey": true,
    "printResults": true,
    "printInputData": true,
    "printExecutiveSummary": true,
    "printEnergySummary": true,
    "printLossesSummary": true,
    "printReportOpportunityPayback": true,
    "printReportOpportunitySummary": true,
    "printSsmtRollup": true,
    "printWasteWaterRollup": true,
    "printDetailedResults": true,
    "printReportDiagram": true,
    "printAll": true,
    "co2SavingsEnergyType": "electricity",
    "co2SavingsEnergySource": "Natural Gas",
    "co2SavingsFuelType": "Natural Gas",
    "totalEmissionOutputRate": 401.07,
    "totalFuelEmissionOutputRate": null,
    "electricityUse": 0,
    "eGridRegion": "",
    "eGridSubregion": "U.S. Average",
    "totalEmissionOutput": 0,
    "totalNaturalGasEmissionOutputRate": 53.06,
    "totalCoalEmissionOutputRate": 0,
    "totalOtherEmissionOutputRate": 0,
    "coalFuelType": "Mixed - Industrial Sector",
    "eafOtherFuelSource": "None",
    "otherFuelType": "",
    "userEnteredBaselineEmissions": false,
    "userEnteredModificationEmissions": false,
    "zipcode": "00000",
    "commonRollupUnit": "MMBtu",
    "pumpsRollupUnit": "MWh",
    "fansRollupUnit": "MWh",
    "steamRollupUnit": "MMBtu",
    "wasteWaterRollupUnit": "MWh",
    "compressedAirRollupUnit": "MWh",
    "modifiedDate": new Date("2022-04-27T18:52:10.262Z"),
    "disableCompressedAirTutorial": true,
    facilityInfo: {
        companyName: "ORNL",
        facilityName: "ORNL Test Facility",
        address: {
            street: "1 Bethel Valley Rd.",
            city: "Oak Ridge",
            state: "TN",
            country: "U.S.",
            zip: "37831"
        },
        facilityContact: {
            contactName: "T. Owner",
            phoneNumber: 8655767658,
            email: "t.owner@ornl.com"
        },
        assessmentContact: {
            contactName: "D.O. Energy",
            phoneNumber: 1234567890,
            email: "AMO_ToolHelpDesk@ee.doe.gov"
        },
        date: "Tue Dec 04 2018"
    },
};
