version: 0.2.{build}-{branch}
branches:
  only:
  - develop
image: Visual Studio 2017
install:
- ps: Install-Product node 16
build_script:
- cmd: >-
    npm ci --legacy-peer-deps
    npm run build
test: off