version: 2
jobs:
  build:
    macos:
      xcode: "10.2"
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5.3.0
      - restore-cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save-cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
