export const _dateFormats: Array<{ value: Array<string>, display: string }> = [
    {
        display: 'MM-DD-YYYY 12:00 XM',
        value: [
            'MM/DD/YYYY',
            'MM/DD/YYYY h',
            'MM/DD/YYYY h:mm',
            'MM/DD/YYYY h:mm:ss',
            'MM/DD/YYYY h a',
            'MM/DD/YYYY h:mm a',
            'MM/DD/YYYY h:mm:ss a',
            'MM/DD/YYYY h A',
            'MM/DD/YYYY h:mm A',
            'MM/DD/YYYY h:mm:ss A',
            'MM/DD/YYYY hh',
            'MM/DD/YYYY hh:mm',
            'MM/DD/YYYY hh:mm:ss',
            'MM/DD/YYYY hh a',
            'MM/DD/YYYY hh:mm a',
            'MM/DD/YYYY hh:mm:ss a',
            'MM/DD/YYYY hh A',
            'MM/DD/YYYY hh:mm A',
            'MM/DD/YYYY hh:mm:ss A',
            'M/DD/YYYY',
            'M/DD/YYYY h',
            'M/DD/YYYY h:mm',
            'M/DD/YYYY h:mm:ss',
            'M/DD/YYYY h a',
            'M/DD/YYYY h:mm a',
            'M/DD/YYYY h:mm:ss a',
            'M/DD/YYYY h A',
            'M/DD/YYYY h:mm A',
            'M/DD/YYYY h:mm:ss A',
            'M/DD/YYYY hh',
            'M/DD/YYYY hh:mm',
            'M/DD/YYYY hh:mm:ss',
            'M/DD/YYYY hh a',
            'M/DD/YYYY hh:mm a',
            'M/DD/YYYY hh:mm:ss a',
            'M/DD/YYYY hh A',
            'M/DD/YYYY hh:mm A',
            'M/DD/YYYY hh:mm:ss A',
            'MM/D/YYYY',
            'MM/D/YYYY h',
            'MM/D/YYYY h:mm',
            'MM/D/YYYY h:mm:ss',
            'MM/D/YYYY h a',
            'MM/D/YYYY h:mm a',
            'MM/D/YYYY h:mm:ss a',
            'MM/D/YYYY h A',
            'MM/D/YYYY h:mm A',
            'MM/D/YYYY h:mm:ss A',
            'MM/D/YYYY hh',
            'MM/D/YYYY hh:mm',
            'MM/D/YYYY hh:mm:ss',
            'MM/D/YYYY hh a',
            'MM/D/YYYY hh:mm a',
            'MM/D/YYYY hh:mm:ss a',
            'MM/D/YYYY hh A',
            'MM/D/YYYY hh:mm A',
            'MM/D/YYYY hh:mm:ss A',
            'M/D/YYYY',
            'M/D/YYYY h',
            'M/D/YYYY h:mm',
            'M/D/YYYY h:mm:ss',
            'M/D/YYYY h a',
            'M/D/YYYY h:mm a',
            'M/D/YYYY h:mm:ss a',
            'M/D/YYYY h A',
            'M/D/YYYY h:mm A',
            'M/D/YYYY h:mm:ss A',
            'M/D/YYYY hh',
            'M/D/YYYY hh:mm',
            'M/D/YYYY hh:mm:ss',
            'M/D/YYYY hh a',
            'M/D/YYYY hh:mm a',
            'M/D/YYYY hh:mm:ss a',
            'M/D/YYYY hh A',
            'M/D/YYYY hh:mm A',
            'M/D/YYYY hh:mm:ss A',
            'MM-DD-YYYY',
            'MM-DD-YYYY h',
            'MM-DD-YYYY h:mm',
            'MM-DD-YYYY h:mm:ss',
            'MM-DD-YYYY h a',
            'MM-DD-YYYY h:mm a',
            'MM-DD-YYYY h:mm:ss a',
            'MM-DD-YYYY h A',
            'MM-DD-YYYY h:mm A',
            'MM-DD-YYYY h:mm:ss A',
            'MM-DD-YYYY hh',
            'MM-DD-YYYY hh:mm',
            'MM-DD-YYYY hh:mm:ss',
            'MM-DD-YYYY hh a',
            'MM-DD-YYYY hh:mm a',
            'MM-DD-YYYY hh:mm:ss a',
            'MM-DD-YYYY hh A',
            'MM-DD-YYYY hh:mm A',
            'MM-DD-YYYY hh:mm:ss A',
            'M-DD-YYYY',
            'M-DD-YYYY h',
            'M-DD-YYYY h:mm',
            'M-DD-YYYY h:mm:ss',
            'M-DD-YYYY h a',
            'M-DD-YYYY h:mm a',
            'M-DD-YYYY h:mm:ss a',
            'M-DD-YYYY h A',
            'M-DD-YYYY h:mm A',
            'M-DD-YYYY h:mm:ss A',
            'M-DD-YYYY hh',
            'M-DD-YYYY hh:mm',
            'M-DD-YYYY hh:mm:ss',
            'M-DD-YYYY hh a',
            'M-DD-YYYY hh:mm a',
            'M-DD-YYYY hh:mm:ss a',
            'M-DD-YYYY hh A',
            'M-DD-YYYY hh:mm A',
            'M-DD-YYYY hh:mm:ss A',
            'MM-D-YYYY',
            'MM-D-YYYY h',
            'MM-D-YYYY h:mm',
            'MM-D-YYYY h:mm:ss',
            'MM-D-YYYY h a',
            'MM-D-YYYY h:mm a',
            'MM-D-YYYY h:mm:ss a',
            'MM-D-YYYY h A',
            'MM-D-YYYY h:mm A',
            'MM-D-YYYY h:mm:ss A',
            'MM-D-YYYY hh',
            'MM-D-YYYY hh:mm',
            'MM-D-YYYY hh:mm:ss',
            'MM-D-YYYY hh a',
            'MM-D-YYYY hh:mm a',
            'MM-D-YYYY hh:mm:ss a',
            'MM-D-YYYY hh A',
            'MM-D-YYYY hh:mm A',
            'MM-D-YYYY hh:mm:ss A',
            'M-D-YYYY',
            'M-D-YYYY h',
            'M-D-YYYY h:mm',
            'M-D-YYYY h:mm:ss',
            'M-D-YYYY h a',
            'M-D-YYYY h:mm a',
            'M-D-YYYY h:mm:ss a',
            'M-D-YYYY h A',
            'M-D-YYYY h:mm A',
            'M-D-YYYY h:mm:ss A',
            'M-D-YYYY hh',
            'M-D-YYYY hh:mm',
            'M-D-YYYY hh:mm:ss',
            'M-D-YYYY hh a',
            'M-D-YYYY hh:mm a',
            'M-D-YYYY hh:mm:ss a',
            'M-D-YYYY hh A',
            'M-D-YYYY hh:mm A',
            'M-D-YYYY hh:mm:ss A'
        ]
    },
    {
        display: 'MM-DD-YY 12:00 XM',
        value: [
            'MM/DD/YY',
            'MM/DD/YY h',
            'MM/DD/YY h:mm',
            'MM/DD/YY h:mm:ss',
            'MM/DD/YY h a',
            'MM/DD/YY h:mm a',
            'MM/DD/YY h:mm:ss a',
            'MM/DD/YY h A',
            'MM/DD/YY h:mm A',
            'MM/DD/YY h:mm:ss A',
            'MM/DD/YY hh',
            'MM/DD/YY hh:mm',
            'MM/DD/YY hh:mm:ss',
            'MM/DD/YY hh a',
            'MM/DD/YY hh:mm a',
            'MM/DD/YY hh:mm:ss a',
            'MM/DD/YY hh A',
            'MM/DD/YY hh:mm A',
            'MM/DD/YY hh:mm:ss A',
            'M/DD/YY',
            'M/DD/YY h',
            'M/DD/YY h:mm',
            'M/DD/YY h:mm:ss',
            'M/DD/YY h a',
            'M/DD/YY h:mm a',
            'M/DD/YY h:mm:ss a',
            'M/DD/YY h A',
            'M/DD/YY h:mm A',
            'M/DD/YY h:mm:ss A',
            'M/DD/YY',
            'M/DD/YY hh',
            'M/DD/YY hh:mm',
            'M/DD/YY hh:mm:ss',
            'M/DD/YY hh a',
            'M/DD/YY hh:mm a',
            'M/DD/YY hh:mm:ss a',
            'M/DD/YY hh A',
            'M/DD/YY hh:mm A',
            'M/DD/YY hh:mm:ss A',
            'MM/D/YY h',
            'MM/D/YY h:mm',
            'MM/D/YY h:mm:ss',
            'MM/D/YY h a',
            'MM/D/YY h:mm a',
            'MM/D/YY h:mm:ss a',
            'MM/D/YY h A',
            'MM/D/YY h:mm A',
            'MM/D/YY h:mm:ss A',
            'MM/D/YY',
            'MM/D/YY hh',
            'MM/D/YY hh:mm',
            'MM/D/YY hh:mm:ss',
            'MM/D/YY hh a',
            'MM/D/YY hh:mm a',
            'MM/D/YY hh:mm:ss a',
            'MM/D/YY hh A',
            'MM/D/YY hh:mm A',
            'MM/D/YY hh:mm:ss A',
            'M/D/YY',
            'M/D/YY h',
            'M/D/YY h:mm',
            'M/D/YY h:mm:ss',
            'M/D/YY h a',
            'M/D/YY h:mm a',
            'M/D/YY h:mm:ss a',
            'M/D/YY h A',
            'M/D/YY h:mm A',
            'M/D/YY h:mm:ss A',
            'M/D/YY hh',
            'M/D/YY hh:mm',
            'M/D/YY hh:mm:ss',
            'M/D/YY hh a',
            'M/D/YY hh:mm a',
            'M/D/YY hh:mm:ss a',
            'M/D/YY hh A',
            'M/D/YY hh:mm A',
            'M/D/YY hh:mm:ss A',
            'MM-DD-YY',
            'MM-DD-YY h',
            'MM-DD-YY h:mm',
            'MM-DD-YY h:mm:ss',
            'MM-DD-YY h a',
            'MM-DD-YY h:mm a',
            'MM-DD-YY h:mm:ss a',
            'MM-DD-YY h A',
            'MM-DD-YY h:mm A',
            'MM-DD-YY h:mm:ss A',
            'MM-DD-YY hh',
            'MM-DD-YY hh:mm',
            'MM-DD-YY hh:mm:ss',
            'MM-DD-YY hh a',
            'MM-DD-YY hh:mm a',
            'MM-DD-YY hh:mm:ss a',
            'MM-DD-YY hh A',
            'MM-DD-YY hh:mm A',
            'MM-DD-YY hh:mm:ss A',
            'M-DD-YY',
            'M-DD-YY h',
            'M-DD-YY h:mm',
            'M-DD-YY h:mm:ss',
            'M-DD-YY h a',
            'M-DD-YY h:mm a',
            'M-DD-YY h:mm:ss a',
            'M-DD-YY h A',
            'M-DD-YY h:mm A',
            'M-DD-YY h:mm:ss A',
            'M-DD-YY hh',
            'M-DD-YY hh:mm',
            'M-DD-YY hh:mm:ss',
            'M-DD-YY hh a',
            'M-DD-YY hh:mm a',
            'M-DD-YY hh:mm:ss a',
            'M-DD-YY hh A',
            'M-DD-YY hh:mm A',
            'M-DD-YY hh:mm:ss A',
            'MM-D-YY',
            'MM-D-YY h',
            'MM-D-YY h:mm',
            'MM-D-YY h:mm:ss',
            'MM-D-YY h a',
            'MM-D-YY h:mm a',
            'MM-D-YY h:mm:ss a',
            'MM-D-YY h A',
            'MM-D-YY h:mm A',
            'MM-D-YY h:mm:ss A',
            'MM-D-YY hh',
            'MM-D-YY hh:mm',
            'MM-D-YY hh:mm:ss',
            'MM-D-YY hh a',
            'MM-D-YY hh:mm a',
            'MM-D-YY hh:mm:ss a',
            'MM-D-YY hh A',
            'MM-D-YY hh:mm A',
            'MM-D-YY hh:mm:ss A',
            'M-D-YY',
            'M-D-YY h',
            'M-D-YY h:mm',
            'M-D-YY h:mm:ss',
            'M-D-YY h a',
            'M-D-YY h:mm a',
            'M-D-YY h:mm:ss a',
            'M-D-YY h A',
            'M-D-YY h:mm A',
            'M-D-YY h:mm:ss A',
            'M-D-YY hh',
            'M-D-YY hh:mm',
            'M-D-YY hh:mm:ss',
            'M-D-YY hh a',
            'M-D-YY hh:mm a',
            'M-D-YY hh:mm:ss a',
            'M-D-YY hh A',
            'M-D-YY hh:mm A',
            'M-D-YY hh:mm:ss A',
        ]
    },
    {
        display: 'DD-MM-YYYY 12:00 XM',
        value: [
            'DD/MM/YYYY',
            'DD/MM/YYYY h',
            'DD/MM/YYYY h:mm',
            'DD/MM/YYYY h:mm:ss',
            'DD/MM/YYYY h a',
            'DD/MM/YYYY h:mm a',
            'DD/MM/YYYY h:mm:ss a',
            'DD/MM/YYYY h A',
            'DD/MM/YYYY h:mm A',
            'DD/MM/YYYY h:mm:ss A',
            'DD/MM/YYYY hh',
            'DD/MM/YYYY hh:mm',
            'DD/MM/YYYY hh:mm:ss',
            'DD/MM/YYYY hh a',
            'DD/MM/YYYY hh:mm a',
            'DD/MM/YYYY hh:mm:ss a',
            'DD/MM/YYYY hh A',
            'DD/MM/YYYY hh:mm A',
            'DD/MM/YYYY hh:mm:ss A',

            'D/MM/YYYY',
            'D/MM/YYYY h',
            'D/MM/YYYY h:mm',
            'D/MM/YYYY h:mm:ss',
            'D/MM/YYYY h a',
            'D/MM/YYYY h:mm a',
            'D/MM/YYYY h:mm:ss a',
            'D/MM/YYYY h A',
            'D/MM/YYYY h:mm A',
            'D/MM/YYYY h:mm:ss A',
            'D/MM/YYYY hh',
            'D/MM/YYYY hh:mm',
            'D/MM/YYYY hh:mm:ss',
            'D/MM/YYYY hh a',
            'D/MM/YYYY hh:mm a',
            'D/MM/YYYY hh:mm:ss a',
            'D/MM/YYYY hh A',
            'D/MM/YYYY hh:mm A',
            'D/MM/YYYY hh:mm:ss A',

            'DD/M/YYYY',
            'DD/M/YYYY h',
            'DD/M/YYYY h:mm',
            'DD/M/YYYY h:mm:ss',
            'DD/M/YYYY h a',
            'DD/M/YYYY h:mm a',
            'DD/M/YYYY h:mm:ss a',
            'DD/M/YYYY h A',
            'DD/M/YYYY h:mm A',
            'DD/M/YYYY h:mm:ss A',
            'DD/M/YYYY hh',
            'DD/M/YYYY hh:mm',
            'DD/M/YYYY hh:mm:ss',
            'DD/M/YYYY hh a',
            'DD/M/YYYY hh:mm a',
            'DD/M/YYYY hh:mm:ss a',
            'DD/M/YYYY hh A',
            'DD/M/YYYY hh:mm A',
            'DD/M/YYYY hh:mm:ss A',

            'D/M/YYYY',
            'D/M/YYYY h',
            'D/M/YYYY h:mm',
            'D/M/YYYY h:mm:ss',
            'D/M/YYYY h a',
            'D/M/YYYY h:mm a',
            'D/M/YYYY h:mm:ss a',
            'D/M/YYYY h A',
            'D/M/YYYY h:mm A',
            'D/M/YYYY h:mm:ss A',
            'D/M/YYYY hh',
            'D/M/YYYY hh:mm',
            'D/M/YYYY hh:mm:ss',
            'D/M/YYYY hh a',
            'D/M/YYYY hh:mm a',
            'D/M/YYYY hh:mm:ss a',
            'D/M/YYYY hh A',
            'D/M/YYYY hh:mm A',
            'D/M/YYYY hh:mm:ss A',

            'DD-MM-YYYY',
            'DD-MM-YYYY h',
            'DD-MM-YYYY h:mm',
            'DD-MM-YYYY h:mm:ss',
            'DD-MM-YYYY h a',
            'DD-MM-YYYY h:mm a',
            'DD-MM-YYYY h:mm:ss a',
            'DD-MM-YYYY h A',
            'DD-MM-YYYY h:mm A',
            'DD-MM-YYYY h:mm:ss A',
            'DD-MM-YYYY hh',
            'DD-MM-YYYY hh:mm',
            'DD-MM-YYYY hh:mm:ss',
            'DD-MM-YYYY hh a',
            'DD-MM-YYYY hh:mm a',
            'DD-MM-YYYY hh:mm:ss a',
            'DD-MM-YYYY hh A',
            'DD-MM-YYYY hh:mm A',
            'DD-MM-YYYY hh:mm:ss A',

            'D-MM-YYYY',
            'D-MM-YYYY h',
            'D-MM-YYYY h:mm',
            'D-MM-YYYY h:mm:ss',
            'D-MM-YYYY h a',
            'D-MM-YYYY h:mm a',
            'D-MM-YYYY h:mm:ss a',
            'D-MM-YYYY h A',
            'D-MM-YYYY h:mm A',
            'D-MM-YYYY h:mm:ss A',
            'D-MM-YYYY hh',
            'D-MM-YYYY hh:mm',
            'D-MM-YYYY hh:mm:ss',
            'D-MM-YYYY hh a',
            'D-MM-YYYY hh:mm a',
            'D-MM-YYYY hh:mm:ss a',
            'D-MM-YYYY hh A',
            'D-MM-YYYY hh:mm A',
            'D-MM-YYYY hh:mm:ss A',

            'DD-M-YYYY',
            'DD-M-YYYY h',
            'DD-M-YYYY h:mm',
            'DD-M-YYYY h:mm:ss',
            'DD-M-YYYY h a',
            'DD-M-YYYY h:mm a',
            'DD-M-YYYY h:mm:ss a',
            'DD-M-YYYY h A',
            'DD-M-YYYY h:mm A',
            'DD-M-YYYY h:mm:ss A',
            'DD-M-YYYY hh',
            'DD-M-YYYY hh:mm',
            'DD-M-YYYY hh:mm:ss',
            'DD-M-YYYY hh a',
            'DD-M-YYYY hh:mm a',
            'DD-M-YYYY hh:mm:ss a',
            'DD-M-YYYY hh A',
            'DD-M-YYYY hh:mm A',
            'DD-M-YYYY hh:mm:ss A',
            
            'D-M-YYYY',
            'D-M-YYYY h',
            'D-M-YYYY h:mm',
            'D-M-YYYY h:mm:ss',
            'D-M-YYYY h a',
            'D-M-YYYY h:mm a',
            'D-M-YYYY h:mm:ss a',
            'D-M-YYYY h A',
            'D-M-YYYY h:mm A',
            'D-M-YYYY h:mm:ss A',
            'D-M-YYYY hh',
            'D-M-YYYY hh:mm',
            'D-M-YYYY hh:mm:ss',
            'D-M-YYYY hh a',
            'D-M-YYYY hh:mm a',
            'D-M-YYYY hh:mm:ss a',
            'D-M-YYYY hh A',
            'D-M-YYYY hh:mm A',
            'D-M-YYYY hh:mm:ss A',
        ]
    },
    {
        display: 'DD-MM-YY 12:00 XM',
        value: [
            'DD/MM/YY',
            'DD/MM/YY h',
            'DD/MM/YY h:mm',
            'DD/MM/YY h:mm:ss',
            'DD/MM/YY h a',
            'DD/MM/YY h:mm a',
            'DD/MM/YY h:mm:ss a',
            'DD/MM/YY h A',
            'DD/MM/YY h:mm A',
            'DD/MM/YY h:mm:ss A',
            'DD/MM/YY hh',
            'DD/MM/YY hh:mm',
            'DD/MM/YY hh:mm:ss',
            'DD/MM/YY hh a',
            'DD/MM/YY hh:mm a',
            'DD/MM/YY hh:mm:ss a',
            'DD/MM/YY hh A',
            'DD/MM/YY hh:mm A',
            'DD/MM/YY hh:mm:ss A',

            'D/MM/YY',
            'D/MM/YY h',
            'D/MM/YY h:mm',
            'D/MM/YY h:mm:ss',
            'D/MM/YY h a',
            'D/MM/YY h:mm a',
            'D/MM/YY h:mm:ss a',
            'D/MM/YY h A',
            'D/MM/YY h:mm A',
            'D/MM/YY h:mm:ss A',
            'D/MM/YY hh',
            'D/MM/YY hh:mm',
            'D/MM/YY hh:mm:ss',
            'D/MM/YY hh a',
            'D/MM/YY hh:mm a',
            'D/MM/YY hh:mm:ss a',
            'D/MM/YY hh A',
            'D/MM/YY hh:mm A',
            'D/MM/YY hh:mm:ss A',

            'DD/M/YY',
            'DD/M/YY h',
            'DD/M/YY h:mm',
            'DD/M/YY h:mm:ss',
            'DD/M/YY h a',
            'DD/M/YY h:mm a',
            'DD/M/YY h:mm:ss a',
            'DD/M/YY h A',
            'DD/M/YY h:mm A',
            'DD/M/YY h:mm:ss A',
            'DD/M/YY hh',
            'DD/M/YY hh:mm',
            'DD/M/YY hh:mm:ss',
            'DD/M/YY hh a',
            'DD/M/YY hh:mm a',
            'DD/M/YY hh:mm:ss a',
            'DD/M/YY hh A',
            'DD/M/YY hh:mm A',
            'DD/M/YY hh:mm:ss A',

            'D/M/YY',
            'D/M/YY h',
            'D/M/YY h:mm',
            'D/M/YY h:mm:ss',
            'D/M/YY h a',
            'D/M/YY h:mm a',
            'D/M/YY h:mm:ss a',
            'D/M/YY h A',
            'D/M/YY h:mm A',
            'D/M/YY h:mm:ss A',
            'D/M/YY hh',
            'D/M/YY hh:mm',
            'D/M/YY hh:mm:ss',
            'D/M/YY hh a',
            'D/M/YY hh:mm a',
            'D/M/YY hh:mm:ss a',
            'D/M/YY hh A',
            'D/M/YY hh:mm A',
            'D/M/YY hh:mm:ss A',

            'DD-MM-YY',
            'DD-MM-YY h',
            'DD-MM-YY h:mm',
            'DD-MM-YY h:mm:ss',
            'DD-MM-YY h a',
            'DD-MM-YY h:mm a',
            'DD-MM-YY h:mm:ss a',
            'DD-MM-YY h A',
            'DD-MM-YY h:mm A',
            'DD-MM-YY h:mm:ss A',
            'DD-MM-YY',
            'DD-MM-YY hh',
            'DD-MM-YY hh:mm',
            'DD-MM-YY hh:mm:ss',
            'DD-MM-YY hh a',
            'DD-MM-YY hh:mm a',
            'DD-MM-YY hh:mm:ss a',
            'DD-MM-YY hh A',
            'DD-MM-YY hh:mm A',
            'DD-MM-YY hh:mm:ss A',

            'D-MM-YY',
            'D-MM-YY h',
            'D-MM-YY h:mm',
            'D-MM-YY h:mm:ss',
            'D-MM-YY h a',
            'D-MM-YY h:mm a',
            'D-MM-YY h:mm:ss a',
            'D-MM-YY h A',
            'D-MM-YY h:mm A',
            'D-MM-YY h:mm:ss A',
            'D-MM-YY',
            'D-MM-YY hh',
            'D-MM-YY hh:mm',
            'D-MM-YY hh:mm:ss',
            'D-MM-YY hh a',
            'D-MM-YY hh:mm a',
            'D-MM-YY hh:mm:ss a',
            'D-MM-YY hh A',
            'D-MM-YY hh:mm A',
            'D-MM-YY hh:mm:ss A',

            'DD-M-YY',
            'DD-M-YY h',
            'DD-M-YY h:mm',
            'DD-M-YY h:mm:ss',
            'DD-M-YY h a',
            'DD-M-YY h:mm a',
            'DD-M-YY h:mm:ss a',
            'DD-M-YY h A',
            'DD-M-YY h:mm A',
            'DD-M-YY h:mm:ss A',
            'DD-M-YY',
            'DD-M-YY hh',
            'DD-M-YY hh:mm',
            'DD-M-YY hh:mm:ss',
            'DD-M-YY hh a',
            'DD-M-YY hh:mm a',
            'DD-M-YY hh:mm:ss a',
            'DD-M-YY hh A',
            'DD-M-YY hh:mm A',
            'DD-M-YY hh:mm:ss A',

            'D-M-YY',
            'D-M-YY h',
            'D-M-YY h:mm',
            'D-M-YY h:mm:ss',
            'D-M-YY h a',
            'D-M-YY h:mm a',
            'D-M-YY h:mm:ss a',
            'D-M-YY h A',
            'D-M-YY h:mm A',
            'D-M-YY h:mm:ss A',
            'D-M-YY',
            'D-M-YY hh',
            'D-M-YY hh:mm',
            'D-M-YY hh:mm:ss',
            'D-M-YY hh a',
            'D-M-YY hh:mm a',
            'D-M-YY hh:mm:ss a',
            'D-M-YY hh A',
            'D-M-YY hh:mm A',
            'D-M-YY hh:mm:ss A',
        ]
    },
    {
        display: 'MM-DD-YYYY 24:00',
        value: [
            'MM/DD/YYYY',
            'MM/DD/YYYY H',
            'MM/DD/YYYY H:mm',
            'MM/DD/YYYY H:mm:ss',
            'MM/DD/YYYY HH',
            'MM/DD/YYYY HH:mm',
            'MM/DD/YYYY HH:mm:ss',

            'M/DD/YYYY',
            'M/DD/YYYY H',
            'M/DD/YYYY H:mm',
            'M/DD/YYYY H:mm:ss',
            'M/DD/YYYY HH',
            'M/DD/YYYY HH:mm',
            'M/DD/YYYY HH:mm:ss',

            'MM/D/YYYY',
            'MM/D/YYYY H',
            'MM/D/YYYY H:mm',
            'MM/D/YYYY H:mm:ss',
            'MM/D/YYYY HH',
            'MM/D/YYYY HH:mm',
            'MM/D/YYYY HH:mm:ss',

            'M/D/YYYY',
            'M/D/YYYY H',
            'M/D/YYYY H:mm',
            'M/D/YYYY H:mm:ss',
            'M/D/YYYY HH',
            'M/D/YYYY HH:mm',
            'M/D/YYYY HH:mm:ss',

            'MM-DD-YYYY',
            'MM-DD-YYYY H',
            'MM-DD-YYYY H:mm',
            'MM-DD-YYYY H:mm:ss',
            'MM-DD-YYYY HH',
            'MM-DD-YYYY HH:mm',
            'MM-DD-YYYY HH:mm:ss',

            'M-DD-YYYY',
            'M-DD-YYYY H',
            'M-DD-YYYY H:mm',
            'M-DD-YYYY H:mm:ss',
            'M-DD-YYYY HH',
            'M-DD-YYYY HH:mm',
            'M-DD-YYYY HH:mm:ss',

            'MM-D-YYYY',
            'MM-D-YYYY H',
            'MM-D-YYYY H:mm',
            'MM-D-YYYY H:mm:ss',
            'MM-D-YYYY HH',
            'MM-D-YYYY HH:mm',
            'MM-D-YYYY HH:mm:ss',

            'M-D-YYYY',
            'M-D-YYYY H',
            'M-D-YYYY H:mm',
            'M-D-YYYY H:mm:ss',
            'M-D-YYYY HH',
            'M-D-YYYY HH:mm',
            'M-D-YYYY HH:mm:ss'
        ]
    },
    {
        display: 'MM-DD-YY 24:00',
        value: [
            'MM/DD/YY',
            'MM/DD/YY H',
            'MM/DD/YY H:mm',
            'MM/DD/YY H:mm:ss',
            'MM/DD/YY HH',
            'MM/DD/YY HH:mm',
            'MM/DD/YY HH:mm:ss',
            'M/DD/YY',
            'M/DD/YY H',
            'M/DD/YY H:mm',
            'M/DD/YY H:mm:ss',
            'M/DD/YY HH',
            'M/DD/YY HH:mm',
            'M/DD/YY HH:mm:ss',
            'MM/D/YY',
            'MM/D/YY H',
            'MM/D/YY H:mm',
            'MM/D/YY H:mm:ss',
            'MM/D/YY HH',
            'MM/D/YY HH:mm',
            'MM/D/YY HH:mm:ss',
            'M/D/YY',
            'M/D/YY H',
            'M/D/YY H:mm',
            'M/D/YY H:mm:ss',
            'M/D/YY HH',
            'M/D/YY HH:mm',
            'M/D/YY HH:mm:ss',

            'MM-DD-YY',
            'MM-DD-YY H',
            'MM-DD-YY H:mm',
            'MM-DD-YY H:mm:ss',
            'MM-DD-YY HH',
            'MM-DD-YY HH:mm',
            'MM-DD-YY HH:mm:ss',
            'M-DD-YY',
            'M-DD-YY H',
            'M-DD-YY H:mm',
            'M-DD-YY H:mm:ss',
            'M-DD-YY HH',
            'M-DD-YY HH:mm',
            'M-DD-YY HH:mm:ss',
            'MM-D-YY',
            'MM-D-YY H',
            'MM-D-YY H:mm',
            'MM-D-YY H:mm:ss',
            'MM-D-YY HH',
            'MM-D-YY HH:mm',
            'MM-D-YY HH:mm:ss',
            'M-D-YY',
            'M-D-YY H',
            'M-D-YY H:mm',
            'M-D-YY H:mm:ss',
            'M-D-YY HH',
            'M-D-YY HH:mm',
            'M-D-YY HH:mm:ss',
        ]
    },
    {
        display: 'DD-MM-YYYY 24:00',
        value: [
            'DD/MM/YYYY',
            'DD/MM/YYYY H',
            'DD/MM/YYYY H:mm',
            'DD/MM/YYYY H:mm:ss',
            'DD/MM/YYYY HH',
            'DD/MM/YYYY HH:mm',
            'DD/MM/YYYY HH:mm:ss',
            'DD/M/YYYY',
            'DD/M/YYYY H',
            'DD/M/YYYY H:mm',
            'DD/M/YYYY H:mm:ss',
            'DD/M/YYYY HH',
            'DD/M/YYYY HH:mm',
            'DD/M/YYYY HH:mm:ss',
            'D/MM/YYYY',
            'D/MM/YYYY H',
            'D/MM/YYYY H:mm',
            'D/MM/YYYY H:mm:ss',
            'D/MM/YYYY HH',
            'D/MM/YYYY HH:mm',
            'D/MM/YYYY HH:mm:ss',
            'D/M/YYYY',
            'D/M/YYYY H',
            'D/M/YYYY H:mm',
            'D/M/YYYY H:mm:ss',
            'D/M/YYYY HH',
            'D/M/YYYY HH:mm',
            'D/M/YYYY HH:mm:ss',

            'DD-MM-YYYY',
            'DD-MM-YYYY H',
            'DD-MM-YYYY H:mm',
            'DD-MM-YYYY H:mm:ss',
            'DD-MM-YYYY HH',
            'DD-MM-YYYY HH:mm',
            'DD-MM-YYYY HH:mm:ss',
            'D-MM-YYYY',
            'D-MM-YYYY H',
            'D-MM-YYYY H:mm',
            'D-MM-YYYY H:mm:ss',
            'D-MM-YYYY HH',
            'D-MM-YYYY HH:mm',
            'D-MM-YYYY HH:mm:ss',
            'DD-M-YYYY',
            'DD-M-YYYY H',
            'DD-M-YYYY H:mm',
            'DD-M-YYYY H:mm:ss',
            'DD-M-YYYY HH',
            'DD-M-YYYY HH:mm',
            'DD-M-YYYY HH:mm:ss',
            'D-M-YYYY',
            'D-M-YYYY H',
            'D-M-YYYY H:mm',
            'D-M-YYYY H:mm:ss',
            'D-M-YYYY HH',
            'D-M-YYYY HH:mm',
            'D-M-YYYY HH:mm:ss',
        ]
    },
    {
        display: 'DD-MM-YY 24:00',
        value: [
            'DD/MM/YY',
            'DD/MM/YY H',
            'DD/MM/YY H:mm',
            'DD/MM/YY H:mm:ss',
            'DD/MM/YY HH',
            'DD/MM/YY HH:mm',
            'DD/MM/YY HH:mm:ss',
            'D/MM/YY',
            'D/MM/YY H',
            'D/MM/YY H:mm',
            'D/MM/YY H:mm:ss',
            'D/MM/YY HH',
            'D/MM/YY HH:mm',
            'D/MM/YY HH:mm:ss',
            'DD/M/YY',
            'DD/M/YY H',
            'DD/M/YY H:mm',
            'DD/M/YY H:mm:ss',
            'DD/M/YY HH',
            'DD/M/YY HH:mm',
            'DD/M/YY HH:mm:ss',
            'D/M/YY',
            'D/M/YY H',
            'D/M/YY H:mm',
            'D/M/YY H:mm:ss',
            'D/M/YY HH',
            'D/M/YY HH:mm',
            'D/M/YY HH:mm:ss',
            'DD-MM-YY',
            'DD-MM-YY H',
            'DD-MM-YY H:mm',
            'DD-MM-YY H:mm:ss',
            'DD-MM-YY HH',
            'DD-MM-YY HH:mm',
            'DD-MM-YY HH:mm:ss',
            'D-MM-YY',
            'D-MM-YY H',
            'D-MM-YY H:mm',
            'D-MM-YY H:mm:ss',
            'D-MM-YY HH',
            'D-MM-YY HH:mm',
            'D-MM-YY HH:mm:ss',
            'DD-M-YY',
            'DD-M-YY H',
            'DD-M-YY H:mm',
            'DD-M-YY H:mm:ss',
            'DD-M-YY HH',
            'DD-M-YY HH:mm',
            'DD-M-YY HH:mm:ss',
            'D-M-YY',
            'D-M-YY H',
            'D-M-YY H:mm',
            'D-M-YY H:mm:ss',
            'D-M-YY HH',
            'D-M-YY HH:mm',
            'D-M-YY HH:mm:ss',
        ]
    },
    {
        display: 'YYYY-MM-DD 12:00 XM',
        value: [
            'YYYY/MM/DD',
            'YYYY/MM/DD h',
            'YYYY/MM/DD h:mm',
            'YYYY/MM/DD h:mm:ss',
            'YYYY/MM/DD h a',
            'YYYY/MM/DD h:mm a',
            'YYYY/MM/DD h:mm:ss a',
            'YYYY/MM/DD h A',
            'YYYY/MM/DD h:mm A',
            'YYYY/MM/DD h:mm:ss A',
            'YYYY/MM/DD hh',
            'YYYY/MM/DD hh:mm',
            'YYYY/MM/DD hh:mm:ss',
            'YYYY/MM/DD hh a',
            'YYYY/MM/DD hh:mm a',
            'YYYY/MM/DD hh:mm:ss a',
            'YYYY/MM/DD hh A',
            'YYYY/MM/DD hh:mm A',
            'YYYY/MM/DD hh:mm:ss A',

            'YYYY/M/DD',
            'YYYY/M/DD h',
            'YYYY/M/DD h:mm',
            'YYYY/M/DD h:mm:ss',
            'YYYY/M/DD h a',
            'YYYY/M/DD h:mm a',
            'YYYY/M/DD h:mm:ss a',
            'YYYY/M/DD h A',
            'YYYY/M/DD h:mm A',
            'YYYY/M/DD h:mm:ss A',
            'YYYY/M/DD hh',
            'YYYY/M/DD hh:mm',
            'YYYY/M/DD hh:mm:ss',
            'YYYY/M/DD hh a',
            'YYYY/M/DD hh:mm a',
            'YYYY/M/DD hh:mm:ss a',
            'YYYY/M/DD hh A',
            'YYYY/M/DD hh:mm A',
            'YYYY/M/DD hh:mm:ss A',

            'YYYY/MM/D',
            'YYYY/MM/D h',
            'YYYY/MM/D h:mm',
            'YYYY/MM/D h:mm:ss',
            'YYYY/MM/D h a',
            'YYYY/MM/D h:mm a',
            'YYYY/MM/D h:mm:ss a',
            'YYYY/MM/D h A',
            'YYYY/MM/D h:mm A',
            'YYYY/MM/D h:mm:ss A',
            'YYYY/MM/D hh',
            'YYYY/MM/D hh:mm',
            'YYYY/MM/D hh:mm:ss',
            'YYYY/MM/D hh a',
            'YYYY/MM/D hh:mm a',
            'YYYY/MM/D hh:mm:ss a',
            'YYYY/MM/D hh A',
            'YYYY/MM/D hh:mm A',
            'YYYY/MM/D hh:mm:ss A',
            'YYYY/M/D',
            'YYYY/M/D h',
            'YYYY/M/D h:mm',
            'YYYY/M/D h:mm:ss',
            'YYYY/M/D h a',
            'YYYY/M/D h:mm a',
            'YYYY/M/D h:mm:ss a',
            'YYYY/M/D h A',
            'YYYY/M/D h:mm A',
            'YYYY/M/D h:mm:ss A',
            'YYYY/M/D hh',
            'YYYY/M/D hh:mm',
            'YYYY/M/D hh:mm:ss',
            'YYYY/M/D hh a',
            'YYYY/M/D hh:mm a',
            'YYYY/M/D hh:mm:ss a',
            'YYYY/M/D hh A',
            'YYYY/M/D hh:mm A',
            'YYYY/M/D hh:mm:ss A',

            'YYYY-MM-DD',
            'YYYY-MM-DD h',
            'YYYY-MM-DD h:mm',
            'YYYY-MM-DD h:mm:ss',
            'YYYY-MM-DD h a',
            'YYYY-MM-DD h:mm a',
            'YYYY-MM-DD h:mm:ss a',
            'YYYY-MM-DD h A',
            'YYYY-MM-DD h:mm A',
            'YYYY-MM-DD h:mm:ss A',
            'YYYY-MM-DD hh',
            'YYYY-MM-DD hh:mm',
            'YYYY-MM-DD hh:mm:ss',
            'YYYY-MM-DD hh a',
            'YYYY-MM-DD hh:mm a',
            'YYYY-MM-DD hh:mm:ss a',
            'YYYY-MM-DD hh A',
            'YYYY-MM-DD hh:mm A',
            'YYYY-MM-DD hh:mm:ss A',

            'YYYY-M-DD',
            'YYYY-M-DD h',
            'YYYY-M-DD h:mm',
            'YYYY-M-DD h:mm:ss',
            'YYYY-M-DD h a',
            'YYYY-M-DD h:mm a',
            'YYYY-M-DD h:mm:ss a',
            'YYYY-M-DD h A',
            'YYYY-M-DD h:mm A',
            'YYYY-M-DD h:mm:ss A',
            'YYYY-M-DD hh',
            'YYYY-M-DD hh:mm',
            'YYYY-M-DD hh:mm:ss',
            'YYYY-M-DD hh a',
            'YYYY-M-DD hh:mm a',
            'YYYY-M-DD hh:mm:ss a',
            'YYYY-M-DD hh A',
            'YYYY-M-DD hh:mm A',
            'YYYY-M-DD hh:mm:ss A',
            
            'YYYY-MM-D',
            'YYYY-MM-D h',
            'YYYY-MM-D h:mm',
            'YYYY-MM-D h:mm:ss',
            'YYYY-MM-D h a',
            'YYYY-MM-D h:mm a',
            'YYYY-MM-D h:mm:ss a',
            'YYYY-MM-D h A',
            'YYYY-MM-D h:mm A',
            'YYYY-MM-D h:mm:ss A',
            'YYYY-MM-D hh',
            'YYYY-MM-D hh:mm',
            'YYYY-MM-D hh:mm:ss',
            'YYYY-MM-D hh a',
            'YYYY-MM-D hh:mm a',
            'YYYY-MM-D hh:mm:ss a',
            'YYYY-MM-D hh A',
            'YYYY-MM-D hh:mm A',
            'YYYY-MM-D hh:mm:ss A',
            
            'YYYY-M-D',
            'YYYY-M-D h',
            'YYYY-M-D h:mm',
            'YYYY-M-D h:mm:ss',
            'YYYY-M-D h a',
            'YYYY-M-D h:mm a',
            'YYYY-M-D h:mm:ss a',
            'YYYY-M-D h A',
            'YYYY-M-D h:mm A',
            'YYYY-M-D h:mm:ss A',
            'YYYY-M-D hh',
            'YYYY-M-D hh:mm',
            'YYYY-M-D hh:mm:ss',
            'YYYY-M-D hh a',
            'YYYY-M-D hh:mm a',
            'YYYY-M-D hh:mm:ss a',
            'YYYY-M-D hh A',
            'YYYY-M-D hh:mm A',
            'YYYY-M-D hh:mm:ss A'
        ]
    },
    {
        display: 'YYYY-DD-MM 12:00 XM',
        value: [
            'YYYY/DD/MM',
            'YYYY/DD/MM h',
            'YYYY/DD/MM h:mm',
            'YYYY/DD/MM h:mm:ss',
            'YYYY/DD/MM h a',
            'YYYY/DD/MM h:mm a',
            'YYYY/DD/MM h:mm:ss a',
            'YYYY/DD/MM h A',
            'YYYY/DD/MM h:mm A',
            'YYYY/DD/MM h:mm:ss A',
            'YYYY/DD/MM hh',
            'YYYY/DD/MM hh:mm',
            'YYYY/DD/MM hh:mm:ss',
            'YYYY/DD/MM hh a',
            'YYYY/DD/MM hh:mm a',
            'YYYY/DD/MM hh:mm:ss a',
            'YYYY/DD/MM hh A',
            'YYYY/DD/MM hh:mm A',
            'YYYY/DD/MM hh:mm:ss A',
            
            'YYYY/D/MM',
            'YYYY/D/MM h',
            'YYYY/D/MM h:mm',
            'YYYY/D/MM h:mm:ss',
            'YYYY/D/MM h a',
            'YYYY/D/MM h:mm a',
            'YYYY/D/MM h:mm:ss a',
            'YYYY/D/MM h A',
            'YYYY/D/MM h:mm A',
            'YYYY/D/MM h:mm:ss A',
            'YYYY/D/MM hh',
            'YYYY/D/MM hh:mm',
            'YYYY/D/MM hh:mm:ss',
            'YYYY/D/MM hh a',
            'YYYY/D/MM hh:mm a',
            'YYYY/D/MM hh:mm:ss a',
            'YYYY/D/MM hh A',
            'YYYY/D/MM hh:mm A',
            'YYYY/D/MM hh:mm:ss A',

            'YYYY/DD/M',
            'YYYY/DD/M h',
            'YYYY/DD/M h:mm',
            'YYYY/DD/M h:mm:ss',
            'YYYY/DD/M h a',
            'YYYY/DD/M h:mm a',
            'YYYY/DD/M h:mm:ss a',
            'YYYY/DD/M h A',
            'YYYY/DD/M h:mm A',
            'YYYY/DD/M h:mm:ss A',
            'YYYY/DD/M hh',
            'YYYY/DD/M hh:mm',
            'YYYY/DD/M hh:mm:ss',
            'YYYY/DD/M hh a',
            'YYYY/DD/M hh:mm a',
            'YYYY/DD/M hh:mm:ss a',
            'YYYY/DD/M hh A',
            'YYYY/DD/M hh:mm A',
            'YYYY/DD/M hh:mm:ss A',
            'YYYY/D/M',
            'YYYY/D/M h',
            'YYYY/D/M h:mm',
            'YYYY/D/M h:mm:ss',
            'YYYY/D/M h a',
            'YYYY/D/M h:mm a',
            'YYYY/D/M h:mm:ss a',
            'YYYY/D/M h A',
            'YYYY/D/M h:mm A',
            'YYYY/D/M h:mm:ss A',
            'YYYY/D/M hh',
            'YYYY/D/M hh:mm',
            'YYYY/D/M hh:mm:ss',
            'YYYY/D/M hh a',
            'YYYY/D/M hh:mm a',
            'YYYY/D/M hh:mm:ss a',
            'YYYY/D/M hh A',
            'YYYY/D/M hh:mm A',
            'YYYY/D/M hh:mm:ss A',

            'YYYY-DD-MM',
            'YYYY-DD-MM h',
            'YYYY-DD-MM h:mm',
            'YYYY-DD-MM h:mm:ss',
            'YYYY-DD-MM h a',
            'YYYY-DD-MM h:mm a',
            'YYYY-DD-MM h:mm:ss a',
            'YYYY-DD-MM h A',
            'YYYY-DD-MM h:mm A',
            'YYYY-DD-MM h:mm:ss A',
            'YYYY-DD-MM hh',
            'YYYY-DD-MM hh:mm',
            'YYYY-DD-MM hh:mm:ss',
            'YYYY-DD-MM hh a',
            'YYYY-DD-MM hh:mm a',
            'YYYY-DD-MM hh:mm:ss a',
            'YYYY-DD-MM hh A',
            'YYYY-DD-MM hh:mm A',
            'YYYY-DD-MM hh:mm:ss A',

            'YYYY-D-MM',
            'YYYY-D-MM h',
            'YYYY-D-MM h:mm',
            'YYYY-D-MM h:mm:ss',
            'YYYY-D-MM h a',
            'YYYY-D-MM h:mm a',
            'YYYY-D-MM h:mm:ss a',
            'YYYY-D-MM h A',
            'YYYY-D-MM h:mm A',
            'YYYY-D-MM h:mm:ss A',
            'YYYY-D-MM hh',
            'YYYY-D-MM hh:mm',
            'YYYY-D-MM hh:mm:ss',
            'YYYY-D-MM hh a',
            'YYYY-D-MM hh:mm a',
            'YYYY-D-MM hh:mm:ss a',
            'YYYY-D-MM hh A',
            'YYYY-D-MM hh:mm A',
            'YYYY-D-MM hh:mm:ss A',

            'YYYY-DD-M',
            'YYYY-DD-M h',
            'YYYY-DD-M h:mm',
            'YYYY-DD-M h:mm:ss',
            'YYYY-DD-M h a',
            'YYYY-DD-M h:mm a',
            'YYYY-DD-M h:mm:ss a',
            'YYYY-DD-M h A',
            'YYYY-DD-M h:mm A',
            'YYYY-DD-M h:mm:ss A',
            'YYYY-DD-M hh',
            'YYYY-DD-M hh:mm',
            'YYYY-DD-M hh:mm:ss',
            'YYYY-DD-M hh a',
            'YYYY-DD-M hh:mm a',
            'YYYY-DD-M hh:mm:ss a',
            'YYYY-DD-M hh A',
            'YYYY-DD-M hh:mm A',
            'YYYY-DD-M hh:mm:ss A',

            'YYYY-D-M',
            'YYYY-D-M h',
            'YYYY-D-M h:mm',
            'YYYY-D-M h:mm:ss',
            'YYYY-D-M h a',
            'YYYY-D-M h:mm a',
            'YYYY-D-M h:mm:ss a',
            'YYYY-D-M h A',
            'YYYY-D-M h:mm A',
            'YYYY-D-M h:mm:ss A',
            'YYYY-D-M hh',
            'YYYY-D-M hh:mm',
            'YYYY-D-M hh:mm:ss',
            'YYYY-D-M hh a',
            'YYYY-D-M hh:mm a',
            'YYYY-D-M hh:mm:ss a',
            'YYYY-D-M hh A',
            'YYYY-D-M hh:mm A',
            'YYYY-D-M hh:mm:ss A'
        ]
    },
    {
        display: 'YYYY-DD-MM 24:00',
        value: [
            'YYYY/DD/MM',
            'YYYY/DD/MM H',
            'YYYY/DD/MM H:mm',
            'YYYY/DD/MM H:mm:ss',
            'YYYY/DD/MM HH',
            'YYYY/DD/MM HH:mm',
            'YYYY/DD/MM HH:mm:ss',
            'YYYY/D/MM',
            'YYYY/D/MM H',
            'YYYY/D/MM H:mm',
            'YYYY/D/MM H:mm:ss',
            'YYYY/D/MM HH',
            'YYYY/D/MM HH:mm',
            'YYYY/D/MM HH:mm:ss',
            'YYYY/DD/M',
            'YYYY/DD/M H',
            'YYYY/DD/M H:mm',
            'YYYY/DD/M H:mm:ss',
            'YYYY/DD/M HH',
            'YYYY/DD/M HH:mm',
            'YYYY/DD/M HH:mm:ss',
            'YYYY/D/M',
            'YYYY/D/M H',
            'YYYY/D/M H:mm',
            'YYYY/D/M H:mm:ss',
            'YYYY/D/M HH',
            'YYYY/D/M HH:mm',
            'YYYY/D/M HH:mm:ss',
            'YYYY-DD-MM',
            'YYYY-DD-MM H',
            'YYYY-DD-MM H:mm',
            'YYYY-DD-MM H:mm:ss',
            'YYYY-DD-MM HH',
            'YYYY-DD-MM HH:mm',
            'YYYY-DD-MM HH:mm:ss',
            'YYYY-D-MM',
            'YYYY-D-MM H',
            'YYYY-D-MM H:mm',
            'YYYY-D-MM H:mm:ss',
            'YYYY-D-MM HH',
            'YYYY-D-MM HH:mm',
            'YYYY-D-MM HH:mm:ss',
            'YYYY-DD-M',
            'YYYY-DD-M H',
            'YYYY-DD-M H:mm',
            'YYYY-DD-M H:mm:ss',
            'YYYY-DD-M HH',
            'YYYY-DD-M HH:mm',
            'YYYY-DD-M HH:mm:ss',
            'YYYY-D-M',
            'YYYY-D-M H',
            'YYYY-D-M H:mm',
            'YYYY-D-M H:mm:ss',
            'YYYY-D-M HH',
            'YYYY-D-M HH:mm',
            'YYYY-D-M HH:mm:ss'
        ]
    },
    {
        display: 'YYYY-MM-DD 24:00',
        value: [
            'YYYY/MM/DD',
            'YYYY/MM/DD H',
            'YYYY/MM/DD H:mm',
            'YYYY/MM/DD H:mm:ss',
            'YYYY/MM/DD HH',
            'YYYY/MM/DD HH:mm',
            'YYYY/MM/DD HH:mm:ss',
            'YYYY/M/DD',
            'YYYY/M/DD H',
            'YYYY/M/DD H:mm',
            'YYYY/M/DD H:mm:ss',
            'YYYY/M/DD HH',
            'YYYY/M/DD HH:mm',
            'YYYY/M/DD HH:mm:ss',
            'YYYY/MM/D',
            'YYYY/MM/D H',
            'YYYY/MM/D H:mm',
            'YYYY/MM/D H:mm:ss',
            'YYYY/MM/D HH',
            'YYYY/MM/D HH:mm',
            'YYYY/MM/D HH:mm:ss',
            'YYYY/M/D',
            'YYYY/M/D H',
            'YYYY/M/D H:mm',
            'YYYY/M/D H:mm:ss',
            'YYYY/M/D HH',
            'YYYY/M/D HH:mm',
            'YYYY/M/D HH:mm:ss',

            'YYYY-MM-DD',
            'YYYY-MM-DD H',
            'YYYY-MM-DD H:mm',
            'YYYY-MM-DD H:mm:ss',
            'YYYY-MM-DD HH',
            'YYYY-MM-DD HH:mm',
            'YYYY-MM-DD HH:mm:ss',
            'YYYY-MM-D',
            'YYYY-MM-D H',
            'YYYY-MM-D H:mm',
            'YYYY-MM-D H:mm:ss',
            'YYYY-MM-D HH',
            'YYYY-MM-D HH:mm',
            'YYYY-MM-D HH:mm:ss',
            'YYYY-M-DD',
            'YYYY-M-DD H',
            'YYYY-M-DD H:mm',
            'YYYY-M-DD H:mm:ss',
            'YYYY-M-DD HH',
            'YYYY-M-DD HH:mm',
            'YYYY-M-DD HH:mm:ss',
            'YYYY-M-D',
            'YYYY-M-D H',
            'YYYY-M-D H:mm',
            'YYYY-M-D H:mm:ss',
            'YYYY-M-D HH',
            'YYYY-M-D HH:mm',
            'YYYY-M-D HH:mm:ss'      
        ]
    },
]