name: CI/CD

on:
  push:
    branches:
      - 'master'
      - 'develop'
  workflow_dispatch:

jobs:
  web:
    uses: ./.github/workflows/web.yml

  electron:
    uses: ./.github/workflows/electron.yml
    secrets: inherit
