name: CI/CD

on:
  push:
    branches: 
      - 'master'
      - 'develop'
  workflow_dispatch:

jobs:
  web:
    uses: ./.github/workflows/web.yml

  # Do not enable yet - not yet implemented
  # electron:
  #   uses: ./.github/workflows/electron.yml
