name: PR Checks

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Node version
        run: echo "BUILD_NODE_VER=$(grep -o -P -m 1 '(?<=node":\s").*(?=")' package.json)" >> $GITHUB_ENV
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.BUILD_NODE_VER }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: |
          find . -name "package-lock.json" -not -path "*/node_modules/*" -not -path "*/dist/*" -exec dirname {} \; | sort -u |
          while read dir; do
            echo "Installing dependencies for: $dir"
            (cd $dir && npm ci $dir);
          done
      - name: Run unit tests
        run: npm test -- --watch=false --no-progress
