name: "Template: Deploy"

on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      backup-dir:
        required: false
        type: string
      deploy-dir:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ${{ inputs.tag }}
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Deploy
        run: |
          if [[ -n "${{ inputs.backup-dir }}" ]]; then
            tar -czf ${{ inputs.backup-dir }}/${{ inputs.app-dir }}_$(date +%F)_${GITHUB_SHA::7}.tar.gz ${{ inputs.deploy-dir }}/${{ inputs.app-dir }}
          fi
          rm -rf ${{ inputs.deploy-dir }}/${{ inputs.app-dir }}/*
          chgrp -R apache ./
          mv -v ./* ${{ inputs.deploy-dir }}/${{ inputs.app-dir }}/
