name: Web

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build-prod-web
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
  
  deploy:
    runs-on: [self-hosted, amo-tools]
    needs: build
    env:
      APACHE_DIR: /var/www/html
      BACKUP_DIR: /opt/actions-runner/backups
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Deploy
        run: |
          tar -czf $BACKUP_DIR/measur_$(printf '%(%Y-%m-%d)T\n' -1)_${GITHUB_SHA::7}.tar.gz $APACHE_DIR/measur
          rm -rf $APACHE_DIR/measur/*
          chgrp -R apache ./
          mv -v ./* $APACHE_DIR/measur/


