/**
 * Generated by the compressed-air regression-test tooling.
 * Edit the per-fixture JSON files and regenerate this registry instead of editing it by hand.
 */
import fixtureManifest from './manifest.json';
import assessment0 from './assessments/ca-real-001.json';
import assessment1 from './assessments/ca-real-002.json';
import assessment2 from './assessments/ca-real-003.json';
import assessment3 from './assessments/ca-real-004.json';
import assessment4 from './assessments/ca-real-005.json';
import assessment5 from './assessments/ca-real-006.json';
import assessment6 from './assessments/ca-real-007.json';
import assessment7 from './assessments/ca-real-008.json';
import assessment8 from './assessments/ca-real-009.json';
import assessment9 from './assessments/ca-real-010.json';
import assessment10 from './assessments/ca-real-011.json';
import assessment11 from './assessments/ca-real-012.json';
import assessment12 from './assessments/ca-real-013.json';
import assessment13 from './assessments/ca-real-014.json';
import assessment14 from './assessments/ca-real-015.json';
import assessment15 from './assessments/ca-real-016.json';
import assessment16 from './assessments/ca-real-017.json';
import assessment17 from './assessments/ca-real-018.json';
import assessment18 from './assessments/ca-real-019.json';
import assessment19 from './assessments/ca-real-020.json';
import assessment20 from './assessments/ca-real-021.json';
import assessment21 from './assessments/ca-real-022.json';
import assessment22 from './assessments/ca-real-023.json';
import assessment23 from './assessments/ca-real-024.json';
import assessment24 from './assessments/ca-real-025.json';
import assessment25 from './assessments/ca-real-026.json';
import assessment26 from './assessments/ca-real-027.json';
import assessment27 from './assessments/ca-real-028.json';
import assessment28 from './assessments/ca-real-029.json';
import assessment29 from './assessments/ca-real-030.json';
import assessment30 from './assessments/ca-real-031.json';
import assessment31 from './assessments/ca-real-032.json';
import assessment32 from './assessments/ca-real-033.json';
import assessment33 from './assessments/ca-real-034.json';
import assessment34 from './assessments/ca-real-035.json';
import assessment35 from './assessments/ca-real-036.json';
import assessment36 from './assessments/ca-real-037.json';
import assessment37 from './assessments/ca-real-038.json';
import assessment38 from './assessments/ca-real-039.json';
import assessment39 from './assessments/ca-real-040.json';
import assessment40 from './assessments/ca-real-041.json';
import assessment41 from './assessments/ca-real-042.json';
import assessment42 from './assessments/ca-real-043.json';
import snapshotManifest0 from './snapshots/pre-pr409-suite-1.2.5/manifest.json';
import snapshot0Fixture0 from './snapshots/pre-pr409-suite-1.2.5/ca-real-001.json';
import snapshot0Fixture1 from './snapshots/pre-pr409-suite-1.2.5/ca-real-002.json';
import snapshot0Fixture2 from './snapshots/pre-pr409-suite-1.2.5/ca-real-003.json';
import snapshot0Fixture3 from './snapshots/pre-pr409-suite-1.2.5/ca-real-004.json';
import snapshot0Fixture4 from './snapshots/pre-pr409-suite-1.2.5/ca-real-005.json';
import snapshot0Fixture5 from './snapshots/pre-pr409-suite-1.2.5/ca-real-006.json';
import snapshot0Fixture6 from './snapshots/pre-pr409-suite-1.2.5/ca-real-007.json';
import snapshot0Fixture7 from './snapshots/pre-pr409-suite-1.2.5/ca-real-008.json';
import snapshot0Fixture8 from './snapshots/pre-pr409-suite-1.2.5/ca-real-009.json';
import snapshot0Fixture9 from './snapshots/pre-pr409-suite-1.2.5/ca-real-010.json';
import snapshot0Fixture10 from './snapshots/pre-pr409-suite-1.2.5/ca-real-011.json';
import snapshot0Fixture11 from './snapshots/pre-pr409-suite-1.2.5/ca-real-012.json';
import snapshot0Fixture12 from './snapshots/pre-pr409-suite-1.2.5/ca-real-013.json';
import snapshot0Fixture13 from './snapshots/pre-pr409-suite-1.2.5/ca-real-014.json';
import snapshot0Fixture14 from './snapshots/pre-pr409-suite-1.2.5/ca-real-015.json';
import snapshot0Fixture15 from './snapshots/pre-pr409-suite-1.2.5/ca-real-016.json';
import snapshot0Fixture16 from './snapshots/pre-pr409-suite-1.2.5/ca-real-017.json';
import snapshot0Fixture17 from './snapshots/pre-pr409-suite-1.2.5/ca-real-018.json';
import snapshot0Fixture18 from './snapshots/pre-pr409-suite-1.2.5/ca-real-019.json';
import snapshot0Fixture19 from './snapshots/pre-pr409-suite-1.2.5/ca-real-020.json';
import snapshot0Fixture20 from './snapshots/pre-pr409-suite-1.2.5/ca-real-021.json';
import snapshot0Fixture21 from './snapshots/pre-pr409-suite-1.2.5/ca-real-022.json';
import snapshot0Fixture22 from './snapshots/pre-pr409-suite-1.2.5/ca-real-023.json';
import snapshot0Fixture23 from './snapshots/pre-pr409-suite-1.2.5/ca-real-024.json';
import snapshot0Fixture24 from './snapshots/pre-pr409-suite-1.2.5/ca-real-025.json';
import snapshot0Fixture25 from './snapshots/pre-pr409-suite-1.2.5/ca-real-026.json';
import snapshot0Fixture26 from './snapshots/pre-pr409-suite-1.2.5/ca-real-027.json';
import snapshot0Fixture27 from './snapshots/pre-pr409-suite-1.2.5/ca-real-028.json';
import snapshot0Fixture28 from './snapshots/pre-pr409-suite-1.2.5/ca-real-029.json';
import snapshot0Fixture29 from './snapshots/pre-pr409-suite-1.2.5/ca-real-030.json';
import snapshot0Fixture30 from './snapshots/pre-pr409-suite-1.2.5/ca-real-031.json';
import snapshot0Fixture31 from './snapshots/pre-pr409-suite-1.2.5/ca-real-032.json';
import snapshot0Fixture32 from './snapshots/pre-pr409-suite-1.2.5/ca-real-033.json';
import snapshot0Fixture33 from './snapshots/pre-pr409-suite-1.2.5/ca-real-034.json';
import snapshot0Fixture34 from './snapshots/pre-pr409-suite-1.2.5/ca-real-035.json';
import snapshot0Fixture35 from './snapshots/pre-pr409-suite-1.2.5/ca-real-036.json';
import snapshot0Fixture36 from './snapshots/pre-pr409-suite-1.2.5/ca-real-037.json';
import snapshot0Fixture37 from './snapshots/pre-pr409-suite-1.2.5/ca-real-038.json';
import snapshot0Fixture38 from './snapshots/pre-pr409-suite-1.2.5/ca-real-039.json';
import snapshot0Fixture39 from './snapshots/pre-pr409-suite-1.2.5/ca-real-040.json';
import snapshot0Fixture40 from './snapshots/pre-pr409-suite-1.2.5/ca-real-041.json';
import snapshot0Fixture41 from './snapshots/pre-pr409-suite-1.2.5/ca-real-042.json';
import snapshot0Fixture42 from './snapshots/pre-pr409-suite-1.2.5/ca-real-043.json';
import snapshot0Fixture43 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-001.json';
import snapshot0Fixture44 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-002.json';
import snapshot0Fixture45 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-003.json';
import snapshot0Fixture46 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-004.json';
import snapshot0Fixture47 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-005.json';
import snapshot0Fixture48 from './snapshots/pre-pr409-suite-1.2.5/ca-synthetic-006.json';

export const regressionTestCorpus = {
  schemaVersion: fixtureManifest.schemaVersion,
  sourceAppVersion: fixtureManifest.sourceAppVersion,
  fixtures: [assessment0, assessment1, assessment2, assessment3, assessment4, assessment5, assessment6, assessment7, assessment8, assessment9, assessment10, assessment11, assessment12, assessment13, assessment14, assessment15, assessment16, assessment17, assessment18, assessment19, assessment20, assessment21, assessment22, assessment23, assessment24, assessment25, assessment26, assessment27, assessment28, assessment29, assessment30, assessment31, assessment32, assessment33, assessment34, assessment35, assessment36, assessment37, assessment38, assessment39, assessment40, assessment41, assessment42],
};

export const regressionTestSnapshots: Record<string, any> = {
  'pre-pr409-suite-1.2.5': {
    schemaVersion: snapshotManifest0.schemaVersion,
    resultSchemaVersion: snapshotManifest0.resultSchemaVersion,
    snapshotName: snapshotManifest0.snapshotName,
    desktopApplicationVersion: snapshotManifest0.desktopApplicationVersion,
    suitePackageVersion: snapshotManifest0.suitePackageVersion,
    sourceMeasurVersion: snapshotManifest0.sourceMeasurVersion,
    scope: snapshotManifest0.scope,
    fixtures: [snapshot0Fixture0, snapshot0Fixture1, snapshot0Fixture2, snapshot0Fixture3, snapshot0Fixture4, snapshot0Fixture5, snapshot0Fixture6, snapshot0Fixture7, snapshot0Fixture8, snapshot0Fixture9, snapshot0Fixture10, snapshot0Fixture11, snapshot0Fixture12, snapshot0Fixture13, snapshot0Fixture14, snapshot0Fixture15, snapshot0Fixture16, snapshot0Fixture17, snapshot0Fixture18, snapshot0Fixture19, snapshot0Fixture20, snapshot0Fixture21, snapshot0Fixture22, snapshot0Fixture23, snapshot0Fixture24, snapshot0Fixture25, snapshot0Fixture26, snapshot0Fixture27, snapshot0Fixture28, snapshot0Fixture29, snapshot0Fixture30, snapshot0Fixture31, snapshot0Fixture32, snapshot0Fixture33, snapshot0Fixture34, snapshot0Fixture35, snapshot0Fixture36, snapshot0Fixture37, snapshot0Fixture38, snapshot0Fixture39, snapshot0Fixture40, snapshot0Fixture41, snapshot0Fixture42, snapshot0Fixture43, snapshot0Fixture44, snapshot0Fixture45, snapshot0Fixture46, snapshot0Fixture47, snapshot0Fixture48],
  },
};

